name = input("input your name: ")
id = input("input your id: ")
major = input("input your major: ")
school = input("input your school: ")
print()
print("name: ", name)
print("id: ", id)
print("major: ", major)
print("school: ", school)
