name = input("input your name: ")
id = input("input your id: ")
major = input("input your major: ")
grade = input("input your grade: ")
print()
print("name: ", name)
print("id: ", id)
print("major: ", major)
print("grade: ", grade)
